In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from conformalization import cp, coverage_and_length

In [52]:
with open("../results/uncertainty/MCP_APS_60.npy", 'rb') as f:
    region = np.load(f)
    softmax_cal = np.load(f)
    label_cal = np.load(f)
    softmax_val = np.load(f)
    label_val = np.load(f)

In [53]:
np.sum(np.all(region == 0, axis = 1))

np.int64(312)

In [43]:
num_empty = region.shape[0] - np.count_nonzero(np.sum(region != 0, axis =1))

In [47]:
np.sum(np.all(region == 0, axis = 1))

np.int64(40)

In [3]:
# define confidence first
n: int = softmax_cal.shape[0]
Id_sort = np.argsort(softmax_cal, axis=1)[:, ::-1]
cum_sum = np.take_along_axis(softmax_cal, Id_sort, axis=1).cumsum(axis=1)
arr_scores = np.take_along_axis(cum_sum, Id_sort.argsort(axis=1), axis=1)

In [4]:
arr_scores

array([[0.85328999, 0.69026172, 0.99357399, 0.99999992],
       [0.99226512, 0.68133682, 0.8561652 , 0.99999999],
       [0.99174012, 0.67354643, 0.86082055, 1.00000004],
       ...,
       [0.72224945, 0.96548511, 0.99760794, 0.99999991],
       [0.72662109, 0.96638118, 0.99766429, 0.99999987],
       [0.68732047, 0.95938054, 0.99730243, 1.00000008]], shape=(2824, 4))

In [8]:
arr_scores

array([0.69026172, 0.68133682, 0.67354643, ..., 0.72224945, 0.72662109,
       0.68732047], shape=(2824,))

In [6]:
label_cal

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], shape=(2824, 1))

In [7]:
arr_scores = arr_scores[np.arange(n), label_cal.flatten()]
confidence_corrected: float = (
            np.ceil((arr_scores.shape[0] + 1) * 0.95) / arr_scores.shape[0]
        )
q_hat = float(np.quantile(arr_scores, confidence_corrected, method="higher"))
print(confidence_corrected)
print(q_hat)

0.9504249291784702
0.993494525551796


In [9]:
# define confidence first
n: int = softmax_val.shape[0]
Id_sort = np.argsort(softmax_val, axis=1)[:, ::-1]
cum_sum = np.take_along_axis(softmax_val, Id_sort, axis=1).cumsum(axis=1)
scores_val = np.take_along_axis(cum_sum, Id_sort.argsort(axis=1), axis=1)

region = softmax_val * (scores_val <= q_hat)

In [10]:
scores_val

array([[0.9777824 , 0.92429179, 0.51694477, 1.00000001],
       [0.98179042, 0.90859073, 0.45949244, 1.00000005],
       [0.98502989, 0.5022282 , 0.87861994, 1.00000001],
       ...,
       [0.78779638, 0.97806789, 0.99843745, 0.99999997],
       [0.77520674, 0.97643903, 0.99834799, 1.00000001],
       [0.77519   , 0.97658336, 0.99836027, 0.99999992]], shape=(2789, 4))

In [11]:
region

array([[0.05349061, 0.40734702, 0.51694477, 0.        ],
       [0.07319969, 0.44909829, 0.45949244, 0.        ],
       [0.10640995, 0.5022282 , 0.37639174, 0.        ],
       ...,
       [0.78779638, 0.19027151, 0.        , 0.        ],
       [0.77520674, 0.20123228, 0.        , 0.        ],
       [0.77519   , 0.20139337, 0.        , 0.        ]], shape=(2789, 4))

In [13]:
cov, length = coverage_and_length(pred_region = region, label = label_val)

In [15]:
length

np.float64(2.42524202223019)

In [21]:
region

array([[0.05349061, 0.40734702, 0.51694477, 0.        ],
       [0.07319969, 0.44909829, 0.45949244, 0.        ],
       [0.10640995, 0.5022282 , 0.37639174, 0.        ],
       ...,
       [0.78779638, 0.19027151, 0.        , 0.        ],
       [0.77520674, 0.20123228, 0.        , 0.        ],
       [0.77519   , 0.20139337, 0.        , 0.        ]], shape=(2789, 4))

In [33]:
region == 0

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       ...,
       [False, False,  True,  True],
       [False, False,  True,  True],
       [False, False,  True,  True]], shape=(2789, 4))

In [ ]:
np.sum(region != 0, axis =1)

array([1, 1, 1, ..., 2, 2, 2], shape=(2789,))

In [38]:
region

array([[0.05349061, 0.40734702, 0.51694477, 0.        ],
       [0.07319969, 0.44909829, 0.45949244, 0.        ],
       [0.10640995, 0.5022282 , 0.37639174, 0.        ],
       ...,
       [0.78779638, 0.19027151, 0.        , 0.        ],
       [0.77520674, 0.20123228, 0.        , 0.        ],
       [0.77519   , 0.20139337, 0.        , 0.        ]], shape=(2789, 4))

In [39]:
np.count_nonzero(np.sum(region != 0, axis =1))

2789

In [31]:
region.shape[0] - np.count_nonzero(np.sum(region != 0, axis =1))

0

In [26]:
np.count_nonzero(np.sum(region == 0, axis =1))

2789

In [20]:
4 - np.count_nonzero(region, axis=1)

array([1, 1, 1, ..., 2, 2, 2], shape=(2789,))

AttributeError: module 'numpy' has no attribute 'count_zero'